const fs = require('fs');
const path = require('path');
const {execSync} = require('child_process');

const generatedDir = path.join(__dirname, 'src/generated');
const specificationDir = path.join(__dirname, '../../../specification');

// 1. Clean generated files
if (fs.existsSync(generatedDir)) {
    for (const file of fs.readdirSync(generatedDir)) {
        if (file.endsWith('.ts')) {
            fs.unlinkSync(path.join(generatedDir, file));
        }
    }
}

// 2. Run buf generate
console.log('Running buf generate...');
execSync(`buf generate ${specificationDir}`, {stdio: 'inherit', cwd: __dirname});

// 3. Generate barrel exports
if (!fs.existsSync(generatedDir)) {
    console.error(`Generated directory not found: ${generatedDir}`);
    process.exit(1);
}

const files = fs.readdirSync(generatedDir);

const exportsContent = files
    .filter(file => file.endsWith('.ts') && file !== 'index.ts')
    .map(file => `export * from "./${file.replace('.ts', '.js')}";`)
    .sort()
    .join('\n');

const header = `// This file is automatically generated by generate-exports.cjs\n// Do not edit this file manually.\n\n`;

fs.writeFileSync(path.join(generatedDir, 'index.ts'), header + exportsContent + '\n');

console.log('Successfully generated gRPC exports in src/generated/index.ts');
